{% set name = "execnet" %}
{% set version = "1.8.0" %}
{% set hash = "b73c5565e517f24b62dea8a5ceac178c661c4309d3aa0c3e420856c072c411b4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
  run:
    - python
    - apipkg >=1.4

test:
  imports:
    - execnet

about:
  home: http://codespeak.net/execnet
  dev_url: https://github.com/pytest-dev/execnet
  doc_url: http://codespeak.net/execnet
  license: MIT
  license_file: LICENSE
  summary: distributed Python deployment and communication

extra:
  recipe-maintainers:
    - nicoddemus
