travis:
  secure:
    BINSTAR_TOKEN: JUf7dTzHIGXMCntDva1QRJiy5uZ905JpCNuinwuI2AHkKIFCXUY8CQwfIxoVEa5faITLHaWC/UJfDDTGL1Z/LgaP2wTKTa+NVQZr1hSMCHCZn/xEk46Zwqi+L9Rxu/7RWzenmMViF/dAsSJD06sX1mwWpSkQ/1aqJIAs5cN9kGRicEu/J7TE1o4y4pxDjAKwXqZX6lObgVePAxPbsGorC61zKWZoF9MS8lC2a5YuiKt9vyOTVfNKLZbbsMaJJLycDMpIJ3QSANR1gkrUDu3BsozavBuc+oWSIkiJs1XeS+poxH8nO46VvtUHc/nSVBPwwDSecpR0F6dF4klaGj+Y+5H+Vu5YY7Fs48Rhh7EDR35zEkQQ5Z6VujGjV6+QkZA6KwVFULVMYIM2hZcTAuXC3Q5/ymIqpg0lY5ASTQAf0FXrIVL6T6jAl2xKcYXiy4fyEITwL9jaCGFOaR41Ty7dECnkq37n77dwtk8+iTLk4Jv1GnxSY/xwsHQWWR4WYBP11aQWOIbZ7XhMNrw0kdks8sUrK/Kv3qQvr5AYhPRKPmOwitQ1TyglpZepvDMtwAnxJl0/Ir11z6OCPod++Y5RE+IyRnZlwrsbzjUb9rkJv2BjY45fhpAmq+tqYaw6syEld9kI4LsX9PONdH7eI6inu+B39Rmal8ZqTmZDiEun1lI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
