travis:
  secure:
    BINSTAR_TOKEN: wZl8m2SNspcY9d9OQAuS1tlil2wP00IHPFX9aGncMoGuD2SaVkmTp4ufNhF87gIDhXo0puWPM9U4j7+I6UFFLH/ZXEgFRIUTHnReOvT3uC4PL/FU6D/XY6dji88MJIIMHy47TI+Nly1hv4y0IQ11+Poj4TUuBoYxPHnIE4dv2jIRsIzp5yufpou6nyPvvuEN/IqLkfl5tT7IrrSe0cez3JxcgxyJxqUS55yQy3y6aRGilvk+noaJ6Kt+bgXiUR+zM0yZ236Ylb2oEI4sqz8Ftz8ylUJRCgGnsBwf+2Ie1U7cv+Zj1rnooxTJsU01wuWXhAOYb8moHDej1MWHD1Ras/4Ng1uzlj3szt7gbblW/bRQlhJ4rN2e8B+gJxdqrkyiYJ9T+2sdiWnuw9GKcRVTgWeFhEuF1tX4I6mY9PO6CsUVpddS9HSZGUf1pxUxCd4OjZmsyVz1g/HeNsMwg1EJupC6KPsltwuH0vpq15sowwlHjCCaqAhdbljiWn/j4TW8KS7rXemAtFN9ZBwK9QlkAGvqEUNnVHlE7O9eDjTrdfwXF32z9U34peXmFuLXZSNRnflySVVofhvex7290tPZTbib+MTrOl/Moj/2YGBdukunaXlmlfYPb4sS1YO2QROZatkEm+wym+JoRHJCKEe65aqu6cyBFcpZZBa+dhfXDh8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
