travis:
  secure:
    BINSTAR_TOKEN: oPGFPvSeVOpUH3XeqedkIbxHhopJrAfHFdtB3ti/KdsRW/tPUI/z8bUBQNlwQvBeHFwMAl/0TTV5ikFujO58dfGXVsZ9JrGpNBIJP1lBomoa3WFq49qIMTaW2BHXai9qvRug0i3QsTcrqMnSEGD2Ssv/+7c4jUD4XToAjXWBfL1hz70NGMvy51slBvX08cln5IDyAok1KzH/B8l9EB/iWyYSOEPIFqUrO6sVECgg1lVrn8HuRY4sElhjhzzgzNZdbJNnk2CUpFwMY4k5OuLw1YIT4AuFRxHWtPY8Lnrna86oSCrfwvRjTS+UudXGO6+2JBcs6l+dSNKNhKRuxHue3lm+CrAzGTr3+KloRiDsvHuLqcsGysdn3izmouUclAyCClOTJsi0oVvU0p8LJdBkiWp7ktQt09PEJyF/JNeJn+kkGazqr4+nfMUCBP5bsgRlJktoDax6Ony9iwtSIOQt6yVv7wj9tURbbNdz+ZtHO6YEL9LQJ0X7NADqiH263aQRZxmrPrzPQ3ut7LPnPy4ItmGFVvLqjwrXdmnBdS9cLJ4ddovLjXlDUrrFN3n/ZrRL+b8SH9YhTaKiZRbCkgjSGpPaMAUGmqizDIv9grkikmjcDVQjB1iwL707mJZuQhEAOP+hSc8JSrC3qplGUX8oZpOVqprkYf0M2NXuoX8MCGU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
