travis:
  secure:
    BINSTAR_TOKEN: IvEziRYMzYBno0fGSQgVfFvEpUiULleqbhwW1nIRYiE5Ijc6plAIzdPLQt4wJeFNzsxIgPZt1qr0C2xvrLbAcOjUIacfltVcaU3XlT6BgLOY+TPJ4VfRLhWI8w6K9yHbKDqkBkjNu1dJvloxjdN3X6ePXdffSW7YAfQyPRUDdmpAQYt0h3Tk6M0IrmCVwixdSw5YSafVH2l2QYs6p3rfyDxJ3MdnzTS2zzUF85xlyuFtEinHgZYDpy3njKMd27JwTrd5EIHU7al6ojvnHQ7UWy3IjgniWi6F9KVGR4Cj82ijQc3LMajQ9Ot+lctj2shX8JB7UDFcjrl2mhELtPwn41296E852P2xMEcQhZaa6r0/msBWVvC7fZJ8BdKcWNoabK/V7AvZs2yRpgdadXR956c9i6p9SQzfRqwv2P6oTT/2s3dhZMa6sw9ThCtLS1JJrctz2V1xVlcNdspeogwUdjj8Ij/F3e4vH5N45s0gufTxdu4guUfJEaY9fRQDvpC+jjy49EI/uh40H6LG1/hOYSWxapCSqWNt5OvuVsjkt27DrBGrDMhwc4aeeL3qThzbVD0GFYdW3ZIQQs7Ig/PmaYquR2VQs4UkdwCMRhoOZoCXBlLPjuIkFO0vO3J4xwaBnhds4+zH7T2HL4m1c3A1kQhWYdSRkytniCR8ONy0m3w=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
