travis:
  secure:
    BINSTAR_TOKEN: qEca0HxLxUmEF0FEcZlTyu1txY6ffNipadBQp5RSvtnx5wFT9eeCoA61H38mGEYcWts3XpyR/6oDUB38Bk/zHfkfdO2OoqHoc+U+h28o4RxmjvSqbrw/zf4pnECQi9xk9SU/Tmpp4ThV42mJ+n8Z3yasVEEpRtu5oxiMSB4OdolyYJjsH0/KzbupstCNnRVEqAMR2c1LIeUktZaBOHjwpgOIobbm/Klwp/j6MV27TQyWYiyFa3YQ5PxN+sAEiWAlr04SrKuggWUb+0j25dTsbDwp5ZbhvOxpqoy8bqiLrOSZvNPF3qwXfXwLV2hTE4Z70RvpFTedytjSPs9CgIljW1aJ1fvosjmwTFaI/xK64PQuavRZgV4y7jbeyfBVMbdD4HfwnzeVn2VntxW7ioUWaXadXrjmZJXzqeYVadCrFapzF4pH0JbwJv9Jys1OCKgIBrPI2jLeo/74zi9qEH+2xgDC9CLdnxaBOPiuDNhJM/i3Kz001m0Vv/Z1Kitr0ZSmlH8NTd0E8MdT48I1j9IBRrPl7cWODiRZHXyJlKVeRA2abM+NlsNeDl6Wqxe+r5K7VyiOdo3MSP8A9yP5H/80H50mLfa41lmScfRIhS/iPVL/9F7v5xHEIqVMIEUvc/wqt97MzU0x/2S0uVO8jmz1LJOmtv96IZrrkHSPuBrAjdo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
