travis:
  secure:
    BINSTAR_TOKEN: Dfi8yoFn6AbPm0gWPByT3lr7KT6SAmIbfUra6OSl/no8CcK6uZWQKkhQc5arQ34ACBURzEve59KJNVlZqW8JbByZ3SejoI/ciERfDvkutBQPM+GD5gGzw9Qh4O6J3aew26w2du+5fPZv2Svg6L7/9JIzdG5PoIe6APs+n2ayNdtAXD2Rk0PSeJKwwQXGJ5jyp8IQSxbh+vsTXmqvLPYLhn9l421SxXoyQcikw9Iiq/0lijKmMrIPOLnoBPqCSQP5XPG+K6I1+YaEdiyL1GaIJWgtYYxdZBssP5tGvtAgBDUwN7uFxJ9Jpxfm9dey5XQBc5OpzrwjPbXDAOUDHaplHFi/gkL/QZFuN/bhmdZNUBONn8ko1js5Yd6EW965yyopcJ0ZRhNyATV9gF9i/Q4wzWZUHykGF4LL6y65wW27jUovEbkNzGHCmWrySSziAZdCNPENYJixAiwLamyoiVxVXQjWQAeC1+bBEUODis9CL/XALMR7YUpxgZg5vhcnB5O+seZT/eA/O/bfw5emsTnef62XRfw8rtTIa2gWMMKsqgyJp8cIJsoiXyhoTMORnIPwq3kpFdjnvM/+14BpnLQtefnRGWhv/iwnhfuaUxIci/gVq+8mHCgBYUeqN5gREGtnonvM+Fua/r33oL/valdIISHMe3gLuOSlEnJm8Wt5di0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
