travis:
  secure:
    BINSTAR_TOKEN: Qe6us77BP3jWxlahtigRe3atnvnOEgD1IHhzGG9VDTNUzNpQt7fO+tacCJVEdbwjcFL8I+/skKJUc7O3Cv8NxZfqgJCpMi0ScG8yAJacgaUP2SIpDjfD+Ady17AuReCv8EJzhbM+/mihRpa2SWdBn6kcOpwEVsxxfgK8zT6NaQKcOoJPzZR62igd47e6Q2ledSA9bFjY/q7QEMeI0Dfp5Nu31ZhRWAiuTN8l0QMN5gO0kq+dQ0WAgMdsiRNdxDEHgGhMlQvvqg2/GJq2USDTVcRaJ1Jfk+NKHZKvl+9uEaDRrDM8uHpOg19walB2MgIfaAVQ9BGXGsZQdmlFpZX6b6IjT1v5OGIiRJuni8mU8Hv4Qktf+n9RzZzgSpsHnVJjnt9pdQ/cdg7uV6VIxIqV0WXnxetIM1RwrQSlf6J2Rqvh8iwb7icsvnLerK9zT1gniTQy5+I2CAC1Khs4xz70cXtbdrn4FsfF5XTr9dz5pQMlAEumO/qUBWSEoAHvYAgIH6kOM42Ty1sMGeS0h9WeeUke7jJ1Cm2H5JZSgTBNVqVDwfDzngXVk88tPlf+JTWA33EMJT9/iAXhcKa14WsBNfZoDxxSNRQ27nMPoVDpgN5suE9UT65hVkXoO2fa/MImWfq9ECBcHs0pNgW9433K9NuSNCvMSmsQLTC2rwmHOQg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
