travis:
  secure:
    BINSTAR_TOKEN: KGWe3TjMgKkyD0bStUVNdESnsV27G7hjMpsBY+IIoEWgz/zhUamgia44g5hoyd4YkHp3EMOGnheUr+jPUh96nbgi3xwzvaTCr6AlmswPzrhVXUI6N/bRTLjhDR2I44zkl0BREhNnXjLRYdC/r3I2QIbAcpv1mIniIHfOiIFfVzEZo+SyS99a7Fq7AoLuy7ub6Oivf326QmotqdZeHk/iMY0ZEvdtZ4/rU7022ZunnTWFSZ7Q8yhLp8AM3ffZKNuH/nxNMlsKYonV7cs4LrRREzVw2L0lIuKGPN+Q06JOLmFnKwGvPUFmBb6XX7EmPFXu/6UXNmjw2SH2mS6tYPDNdz5js0WPqVyu4EV0phpkJ2IUQk881ac69MFzDzm1v1qEuxcHz+yXEQP/usVCWYxm46Ys966GDFIto08VufagcouhQpQi0Ais/To+sRpoaPSIq0RcZbLtpVj+tt+zkbRPI6SaFjGzAZn/Bt2uPs3cIaOzFd2IwlK0PuZcbyWiD/LAIGR16krGKKS9ANCSQj5Sh5WOUL+W12wMxSigm764Cyg2EMdVub9kqJpV1GAmkziENxaOST/v5UKkm3Hjvg8cuiNQ0KD+fjHa6fx5vPo84IQ7dwDENIHrphqY25Q9DWLnx6S3yD7zbFh55Tsy5UvL80k7x2HGEZIg3NUczFK6tjQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
