travis:
  secure:
    BINSTAR_TOKEN: cw+nWefKbuLPODKrXTM1UWsjF/qdALLm1eXr3zE5xPImvVZK5uunJ/a2HQTR2U4ECt1vr4EbjFp9cdklngQnL/ro6e7dETCC+ui+tjVAaQH1uLhxDDVOm9oPE2TgUCEX6ORe+1r2IR0zJMc1mq4rfEmGfznrOjr2sD6n1qrrzhLGD8CThOq7arTjGnRP7HhkWwyOLCw4FDkxat3DoYMf0B4HB38GGRKCiGIc7n+a4lWT79aP/9A3ytuwZiEeCU2i1p0/VfrUhp/0XZhmrKyAUgWPqzdJjUCaTS0x665YU+fSX+DsbzkWqmIDW8ScKs6KotMYLNtTspLuBWU9koujwRbpcEOk8ZQLnHggs0f52Teey/D5aU68OQJdqkcPylviKBD56OWCcezG+Ph5wrYX/4kkYfFbaHJPuRpZcBwoTHYo1QzihXlseZ/3XGh7EJdY25mSu9PsCmBRb0ri1lxZwguU8g8HKtXM2gAmFW+yiFKJPgmbt85ITcngk/RbyExN8p8+MGwBnogspTq0kcMv9ekc1rLzkiL06DYleyVWdmK8qgQgScW9F0A9w/NKG0hjxK3eV+QC1ES6GzSBMMHHT8X9R9xQYtwfbrG6w8GDWjCS/RQX0w9g2ChAUJ21HL3+H/tlcTY/vYnnqFOSd2mF3V8iULrSz5mw9QKpaGdBzdU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
