travis:
  secure:
    BINSTAR_TOKEN: n1ZgqvSun2SmadesgQUyJ7RMrDB3pLW0KKLgtov9B5kFFjnA4JPvNZrN+S7AYiI3pvCpojZWRpxncwp/k8KI/3bNejNQPEA6BI4zlX/JmSFN/pze1ko1xgq00n8IZIfdj14MiqQqtMv+GZiwJXoYltA5+DBdvHKrjAOTq7HJEYtNJNh2YgyXPZTdkDh/Qq6uBMp7MQTaRzs3xMKo02jfwiLUKDgl4Gs/YBeDmy0KlS8oqA26kk2GYHiwZ3vAwcQPxuN/kjFw0K0ZgKgB7blMJ9QSOQbbu3VkL/Ypvy+8WrqF6a0h+Wzy26D/XIuLOof/lW8OfBrrp7NHYcGEL7bmJp+VT5ek7F/+HtUiKWqnjJH/btU1gjPdjqQyqG64uMs5+Pni++aJQLdZxx6CoRhnNGuKSQxtaKYa/99KBaHkQZKL1I+A1eZ6dlIIIpHhRu6FHXvcfYgLQthce1cX7MJ9FyoObvbj34XdNDM3RHBHf3milnAcECpKmLOYpDxSSEDFRjeruk5Z3JauLe56L0FiGY4mBovUPkJ2y2r+Bbi/VvN17z/XxSmFZ7bTRkkHFl/4M6H+RXpL06j0YTTBYyR5yphW/oBgrN0ryoNVRPFL6N8EVftDivElnMzfEMu9Ol+/faeb+8A+B1DZ5j+suJ5Dmlmvj7KmtgUVCjzO0YsNqlQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
