travis:
  secure:
    BINSTAR_TOKEN: WA1N5L1izPLfbuUlul7jlb1l1kgHlB8+1kpITn3/t7F5q6fdKmpv2U/G4IDCVA4JUWcFKjHGSMoRXekaHD9uuRomybE4XeLl66G4M8iSnxYaVEsQcu//daYkMk++9CixLQro+ZhC0cQnWDHAnBs+ExkUOCg1cr0+ipqDRN7O3hYI/oASc993CI67w50cgfGmBOKM31xmGCwl/HXNvfLBSGrFViqEo8ITXPV/PeFnt9p9QfROQ3tGHU3kgcYiylfi6s7XS3SvrTXkTQBuaHDOd00XdaTmaZSLp+DXHw8nqFbDo/0JRTA8PSi9qcHo/7BBuYp2GD2+cqsGWpBRf/lQehPmbb8b02KvAw2txJ6GYBbociknwtZrdNNc/is3so4WDOhD7uEq8kp7Kl6FqcGPZI2PeI4XH0DzhI7UJ4y+AZiamtPExB0O+dweTgxhl6nmsS8ap96Onu29kMq1Cc9rNwPw3aaOJ6c3HybWMvnBZG/g8q5l0YV1Xdcy1bkzEhQlyNBkB2mRjUlH5LNNeZkTxDZIKRlzL5pZ9qH094SME+WZKvRN7zEO4Av9Qcu4BkCsVHwdEyty370A0e52Zmld2Dxw5ywpB2nETA/cjRxzLfYPEjeoTHxJcTQQPCrwOOz3JQb1KB50VrSSDWbh9P68sf9P1JyIRQ4kvwNSntDL0Ao=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
