travis:
  secure:
    BINSTAR_TOKEN: flXppGmYQGMavEQdttY1awnZuq9ZhhPKlynvhebu2I1pPIl67zBxYKRRkHWaZrwSfb8OGI7icl/uOT6kJI2Dx69/xHY5QzudEaOU1wLtItNyJRNFY1GKSXT8DuMrzb++gitB0F7sHfWLUt41uDpY+qkCLlpUVFyiCrq1DjFojvVKTdoeYrv5i0X+Pc/Le5rg+V+9Dh6OjdqDfwtR7FjRf2poeZA9GM1jzEnR+5pGSJyikAL0DVxdrn6Cuv5xZqiMqehmiyNP++gTYMWRyi2KB0Vgme5lS3bt17Jf1YLR13ALQC2CSqrF+xHZdlz1cG9zWfpFhiBnLGWfQLJwLKlO8mGQvTKTDVVWNNMV8t6wJW/M7Lq+p0HTBZ8R+3IXEULfTGKRVmHNnc7Nvu/eb5iiSaSvFjJIwE3CKRqgO9eF018pyUe9187+mWCOqoIx7WddocYhqDqhRD4syLT8vequKNQh7FlgAPOSKudBQo6WGv741qh1a/n2LjftMzYB+5zQQsUoOOubtKGbGgzyluUzc6ItP7YuXVmSz2Lzw5MZw+5cOKqYHFXGmYZh8/Mxmk/bUpOSZ+hlKgpoPJoI21akOtDJULsh0s2aSHk4JUDpZ6kYBbdZ2SGOewxYSxKBuTyJIqBupss9STzYDslTQm5Eorsg8+eMOKuYapCA4fyk8uo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
